# Generated by Django 2.1.5 on 2019-01-10 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='drinking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sample',
            name='labelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_point',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sample',
            name='water_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
